bot:
  token: YOUR_BOT_TOKEN
  prefix: '!'
  client_id: YOUR_CLIENT_ID

game:
  start_date: '2023-06-01T00:00:00'
  end_date: '2023-06-30T23:59:59'
  require_manual_approval: true
  max_team_size: 4
  min_team_count: 2
  time_limit_enabled: true
  time_limit_duration: 72 # hours
  voting_time_limit: 24
  states:
    lobby: 'lobby'
    active: 'active'
    ended: 'ended'

channels:
  guild_id: YOUR_GUILD_ID
  status: STATUS_CHANNEL_ID
  leaderboard: LEADERBOARD_CHANNEL_ID
  voting: VOTING_CHANNEL_ID
  disputes: DISPUTES_CHANNEL_ID

roles:
  game_manager: GAME_MANAGER_ROLE_ID
  player: PLAYER_ROLE_ID

cooldowns:
  command_cooldown: 5 # seconds

rules_file: gameRules.txt